dbt_example:
  outputs:
    dev:
      dbname: "{{ env_var('DBT_DBNAME') }}"
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      pass: "{{ env_var('DBT_PASS') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: "{{ env_var('DBT_USER') }}"
  target: dev
